version: 2

python:
  version: "3.12"
  install:
    - requirements: requirements.txt

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    - command: sphinx-build -T -b html -d _build/doctrees . _build/html